### ISSUE TITLE
Do not include package name in arguments.

### ISSUE THREAD

**Issue by vale981** [40ants/cldomain#1]
I would like an option to generate an output like that:
```
 function (MAKE-TG-BOT token &optional api-url)
```

as opposed to:
```
 function (MAKE-TG-BOT cl-telegram-bot::token &optional cl-telegram-bot::api-url)
```

**Comment by svetlyak40wt** [comment]
I've moved it to the cldomain repository.

**Comment by vale981** [comment]
I've no clue why that ended up in cl-hamcrest.  Sorry.

**Comment by svetlyak40wt** [comment]
Now I understand and think it shouldn't be an option. Just this should be fixed and all function parameters should be printed without a package.

**Comment by svetlyak40wt** [comment]
Feel free to send a pull request with the fix! :-D

**Comment by vale981** [comment]
In the python or the lisp part. (i guess the lisp part :P)
And I really appreciate that you maintain those projects.

**Comment by vale981** [comment]
The fix really is quite trivial :P.

**Comment by svetlyak40wt** [comment]
Thank you, @vale981
